using System;
using System.Collections.Generic;
using System.Text;

namespace AutoMapModel
{
    /// <summary>
    /// 自动根据数据库生成Model文件脚本
    /// 类似DB First
    /// </summary>
    public class AutoGenerateDBModel
    {


    }
}
